import Head from "next/head";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs, huntingCoder blog, hunting coder"/>
        <link rel="icon" href="/favicon.ico" />
        {/* <script src="/sc.js"></script> */}
      </Head>
      {/* <Script src="/sc.js" strategy='lazyOnload'></Script> */}

      <main className={`${styles.main}`}>
        <div className={styles.imagewrap}>
          {/* <Image className={styles.myImg} src="/homeimg.avif" alt='coding image' width={237} height={158} /> */}
          <img className={styles.myImg} src="/homeimg.avif" width={237}  height={158} alt="hunting coder" />
        </div>
        <h1 className={styles.title}>
          <span className="dummy">&lt;HuntingCoder/&gt;</span>
        </h1>
        <div>
          <h2 className={styles.h2}>Latest Blogs</h2>
          <div>
            <h3 className={styles.h3}>How to learn Javascript in 2023?</h3>
            <p className={styles.p}>Javascript is the language used to design logic for the web. Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus impedit dolore totam!</p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div>
            <h3 className={styles.h3}>How to learn Javascript in 2023?</h3>
            <p className={styles.p}>Javascript is the language used to design logic for the web</p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div>
            <h3 className={styles.h3}>How to learn Javascript in 2023?</h3>
            <p className={styles.p}>Javascript is the language used to design logic for the web</p>
            <button className={styles.btn}>Read More</button>
          </div>
        </div>
      </main>
    </div>
  );
}
